# Generated by Django 5.0.6 on 2024-07-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketSales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationmodel",
            name="id",
        ),
        migrations.AddField(
            model_name="locationmodel",
            name="IdNumber",
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locationmodel",
            name="Address",
            field=models.CharField(default="Berlin", max_length=500),
        ),
        migrations.AlterField(
            model_name="locationmodel",
            name="Phone",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name="timeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StartDateTime", models.DateTimeField()),
                (
                    "status_choices",
                    models.IntegerField(
                        choices=[
                            ("Start", "selling is started"),
                            ("End", "selling is finished"),
                            ("Concel", "selling is cancelled"),
                            ("Sales", "selling now"),
                        ]
                    ),
                ),
                (
                    "concertModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ticketSales.concertmodel",
                    ),
                ),
                (
                    "locationModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ticketSales.locationmodel",
                    ),
                ),
            ],
        ),
    ]
