# Generated by Django 5.0.6 on 2024-07-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketSales", "0002_remove_locationmodel_id_locationmodel_idnumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Family", models.CharField(max_length=100)),
                ("ProfileImage", models.ImageField(upload_to="ProfileImages/")),
                (
                    "Gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concertmodel",
            name="poster",
            field=models.ImageField(default="default_poster.jpj", upload_to="posters/"),
        ),
        migrations.AddField(
            model_name="concertmodel",
            name="test",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="timemodel",
            name="status_choices",
            field=models.IntegerField(
                choices=[
                    ("Start", "selling is started"),
                    ("End", "selling is ended"),
                    ("Concel", "selling is cancelled"),
                    ("Sales", "selling now"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="ticketModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticketImage", models.ImageField(upload_to="TicketImages/")),
                ("Name", models.CharField(max_length=100)),
                ("Price", models.IntegerField()),
                (
                    "ProfileModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="ticketSales.profilemodel",
                    ),
                ),
                (
                    "timeModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="ticketSales.timemodel",
                    ),
                ),
            ],
        ),
    ]
